version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "master"
    schedule:
      interval: "monthly"
  - package-ecosystem: "maven"
    directory: "/"
    target-branch: "master"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: com.alibaba:fastjson
        versions: [">=2.0"]
      - dependency-name: spring-boot-starter-parent
        versions: [">=3"]
      - dependency-name: org.springframework.boot.spring-boot-starter-parent
        versions: [">=3"]
      - dependency-name: io.sentry:sentry-spring-boot-starter
        versions: [">=3"]
