version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "master"
    schedule:
      interval: "monthly"
  - package-ecosystem: "maven"
    directory: "/"
    target-branch: "master"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: com.alibaba:fastjson
        versions: ["2.x"]
